# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toiduaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimetus', models.CharField(max_length=50)),
                ('valgud', models.IntegerField(max_length=100)),
                ('rasvad', models.IntegerField(max_length=100)),
                ('sysivesikud', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Toit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimetus', models.CharField(max_length=50)),
                ('toiduained', models.ManyToManyField(to='create.Toiduaine')),
            ],
        ),
    ]
