# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_auto_20170421_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toidukomponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kogus', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('toiduaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.Toiduaine')),
            ],
        ),
        migrations.RemoveField(
            model_name='toit',
            name='toiduained',
        ),
        migrations.AddField(
            model_name='toit',
            name='toidukomponendid',
            field=models.ManyToManyField(db_constraint=django.db.models.deletion.CASCADE, to='create.Toidukomponent'),
        ),
    ]
